clean:
	rm -f *.pyc *~
	rm -f */*.pyc */*~
	rm -f */*/*.pyc */*/*~
	rm -f */*/*/*.pyc */*/*/*~
	rm -f */*/*/*/*.pyc */*/*/*/*~
	rm -f */*/*/*/*/*.pyc */*/*/*/*/*~
	rm -f MANIFEST
	rm -rf build

distclean: clean
	rm -rf dist

picclean: clean
	rm -f *.pic
	rm -f */*.pic
	rm -f */*/*.pic
	rm -f */*/*/*.pic
	rm -f */*/*/*/*.pic
	rm -f */*/*/*/*/*.pic
