package eu.delving.core.metadata;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * A groovy mapping based on a model.
 *
 * @author Gerald de Jong <geralddejong@gmail.com>
 */

@XStreamAlias("metadata-mapping")
public class MetaMapping {

    @XStreamAlias("record-root")
    public String recordRoot;

    @XStreamAlias("constants")
    public Map<String, String> constants = new HashMap<String, String>();

    @XStreamAlias("field-mappings")
    public Map<String, FieldMapping> fieldMappings = new HashMap<String, FieldMapping>();

    @XStreamAlias("field-mapping")
    public static class FieldMapping {

        @XStreamAlias("value-map")
        public Map<String, String> valueMap;

        @XStreamAlias("groovy-code")
        public List<String> code;


        public void setValue(String key, String value) {
            if (valueMap == null) {
                valueMap = new HashMap<String, String>();
            }
            valueMap.put(key, value);
        }

        public void setCode(String code) {
            if (this.code == null) {
                this.code = new ArrayList<String>();
            }
            this.code.clear();
            this.code.addAll(Arrays.asList(code.split("\n")));
        }
    }

    public String generateCode(MetaModel model) {
        final StringBuilder stringBuilder = new StringBuilder();
        Out out = new Out() {
            int indentLevel;

            @Override
            public void line(String line) {
                int spaces = indentLevel * 4;
                while (spaces-- > 0) {
                    stringBuilder.append(' ');
                }
                stringBuilder.append(line).append('\n');
            }

            @Override
            public void indent(int change) {
                indentLevel += change;
            }
        };
        out.line("// Groovy Mapping Code - Generated by SIP-Creator\n");
        out.line("// Constants\n");
        for (Map.Entry<String, String> constantEntry : constants.entrySet()) {
            out.line(String.format("def %s = '%s'\n", constantEntry.getKey(), constantEntry.getValue()));
        }
        out.line("\n// Value Maps\n");
        for (Map.Entry<String, FieldMapping> fieldMappingEntry : fieldMappings.entrySet()) {
            if (fieldMappingEntry.getValue().valueMap != null) {
                String path = mungePath(fieldMappingEntry.getKey());
                out.line(String.format("def %sMap = [\n", path));
                out.indent(1);
                for (Map.Entry<String, String> entry : fieldMappingEntry.getValue().valueMap.entrySet()) {
                    out.line(String.format("'%s':'%s,", entry.getKey(), entry.getValue()));
                }
                out.indent(-1);
                out.line("]");
                out.line(String.format("def %s = { def v = %sMap[it.toString()]; return v ? v : it }\n", path, path));
            }
        }
        out.line("// Builder to create the record\n");
        out.line("output.record {");
        out.indent(1);
        for (MetaNode node : model.nodes) {
            generateCode("", node, out);
        }
        out.indent(-1);
        out.line("}\n");
        return stringBuilder.toString();
    }

    // === private

    private void generateCode(String path, MetaNode node, Out out) {
        out.line(String.format("%s {", node.tag));
        out.indent(1);
        if (node.nodes != null) {
            for (MetaNode subNode : node.nodes) {
                generateCode(path + "/" + node.tag, subNode, out);
            }
        }
        if (node.fields != null) {
            for (MetaField field : node.fields) {
                generateCode(path + "/" + node.tag, field, out);
            }
        }
        out.indent(-1);
        out.line("}");
    }

    private void generateCode(String path, MetaField field, Out out) {
        String fieldPath = path + "/" + field.getTag();
        FieldMapping fieldMapping = fieldMappings.get(fieldPath);
        if (fieldMapping != null) {
            for (String line : fieldMapping.code) {
                if (codeIndent(line) < 0) {
                    out.indent(-1);
                }
                out.line(line);
                if (codeIndent(line) > 0) {
                    out.indent(1);
                }
            }
        }
    }

    private static int codeIndent(String line) {
        int indent = 0;
        for (char c : line.toCharArray()) {
            switch (c) {
                case '}': indent--; break;
                case '{': indent++; break;
            }
        }
        return indent;
    }

    private String mungePath(String path) {
        return path.replaceAll("/", "__");
    }

    interface Out {
        void line(String line);
        void indent(int change);
    }

    // ==== reading and writing

    // observable

    public interface Listener {
        void mappingChanged(MetaMapping metaMapping);
    }

    public void addListener(Listener listener) {
        listeners.add(listener);
    }

    private List<Listener> listeners = new CopyOnWriteArrayList<Listener>();

    private void fireChangeEvent() {
        for (Listener listener : listeners) {
            listener.mappingChanged(this);
        }
    }

    public static MetaMapping read(InputStream inputStream) {
        return (MetaMapping) stream().fromXML(inputStream);
    }

    public static MetaMapping read(String string) {
        return (MetaMapping) stream().fromXML(string);
    }

    public static String toString(MetaMapping spec) {
        return stream().toXML(spec);
    }

    private static XStream stream() {
        XStream stream = new XStream();
        stream.processAnnotations(MetaMapping.class);
        return stream;
    }
}
