/*
 * Copyright 2010 DELVING BV
 *
 *  Licensed under the EUPL, Version 1.0 or? as soon they
 *  will be approved by the European Commission - subsequent
 *  versions of the EUPL (the "Licence");
 *  you may not use this work except in compliance with the
 *  Licence.
 *  You may obtain a copy of the Licence at:
 *
 *  http://ec.europa.eu/idabc/eupl
 *
 *  Unless required by applicable law or agreed to in
 *  writing, software distributed under the Licence is
 *  distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 *  express or implied.
 *  See the Licence for the specific language governing
 *  permissions and limitations under the Licence.
 */

package eu.delving.core.metadata;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;
import org.apache.log4j.Logger;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * A groovy mapping based on a model.
 *
 * @author Gerald de Jong <geralddejong@gmail.com>
 */

@XStreamAlias("record-mapping")
public class RecordMapping {
    @XStreamOmitField
    public boolean dirty;

    @XStreamAlias("record-root")
    public String recordRoot;

    @XStreamAlias("constants")
    public Map<String, String> constants = new HashMap<String, String>();

    @XStreamAlias("field-mappings")
    public Map<String, FieldMapping> fieldMappings = new HashMap<String, FieldMapping>();

    @XStreamAlias("field-mapping")
    public class FieldMapping {

        @XStreamAlias("value-map")
        public Map<String, String> valueMap;

        @XStreamAlias("groovy-code")
        public List<String> code;


        public void setValue(String key, String value) {
            if (valueMap == null) {
                valueMap = new HashMap<String, String>();
            }
            valueMap.put(key, value);
        }

        public void setCode(String code) {
            if (this.code == null) {
                this.code = new ArrayList<String>();
            }
            this.code.clear();
            this.code.addAll(Arrays.asList(code.split("\n")));
        }
    }

    public String generateCode(RecordDefinition recordDefinition) {
        final StringBuilder stringBuilder = new StringBuilder();
        Out out = new Out() {
            int indentLevel;

            @Override
            public void line(String line) {
                int spaces = indentLevel * 4;
                while (spaces-- > 0) {
                    stringBuilder.append(' ');
                }
                stringBuilder.append(line).append('\n');
            }

            @Override
            public void indent(int change) {
                indentLevel += change;
            }
        };
        out.line("// Groovy Mapping Code - Generated by SIP-Creator\n");
        out.line("// Constants\n");
        for (Map.Entry<String, String> constantEntry : constants.entrySet()) {
            out.line(String.format("def %s = '%s'\n", constantEntry.getKey(), constantEntry.getValue()));
        }
        out.line("\n// Value Maps\n");
        for (Map.Entry<String, FieldMapping> fieldMappingEntry : fieldMappings.entrySet()) {
            if (fieldMappingEntry.getValue().valueMap != null) {
                String path = mungePath(fieldMappingEntry.getKey());
                out.line(String.format("def %sMap = [\n", path));
                out.indent(1);
                for (Map.Entry<String, String> entry : fieldMappingEntry.getValue().valueMap.entrySet()) {
                    out.line(String.format("'%s':'%s,", entry.getKey(), entry.getValue()));
                }
                out.indent(-1);
                out.line("]");
                out.line(String.format("def %s = { def v = %sMap[it.toString()]; return v ? v : it }\n", path, path));
            }
        }
        out.line("// Builder to create the record\n");
        out.line("output.");
        out.indent(1);
        Set<String> usedPaths = new TreeSet<String>();
        generateCode("", recordDefinition.root, out, usedPaths);
        out.indent(-1);
        if (usedPaths.size() != fieldMappings.size()) {
            Set<String> unusedPaths = new TreeSet<String>(fieldMappings.keySet());
            unusedPaths.removeAll(usedPaths);
            Logger.getLogger(getClass()).warn("unused paths: "+unusedPaths);
        }
        return stringBuilder.toString();
    }

    public String toString() {
        return stream().toXML(this);
    }

    // === private

    private void generateCode(String path, ElementDefinition element, Out out, Set<String> usedPaths) {
        out.line(String.format("%s {", element.tag));
        out.indent(1);
        if (element.elements != null) {
            for (ElementDefinition subNode : element.elements) {
                generateCode(path + "/" + element.tag, subNode, out, usedPaths);
            }
        }
        if (element.fields != null) {
            for (FieldDefinition fieldDefinition : element.fields) {
                generateCode(path + "/" + element.tag, fieldDefinition, out, usedPaths);
            }
        }
        out.indent(-1);
        out.line("}");
    }

    private void generateCode(String path, FieldDefinition field, Out out, Set<String> usedPaths) {
        String fieldPath = path + "/" + field.getTag();
        FieldMapping fieldMapping = fieldMappings.get(fieldPath);
        if (fieldMapping != null) {
            usedPaths.add(fieldPath);
            for (String line : fieldMapping.code) {
                if (codeIndent(line) < 0) {
                    out.indent(-1);
                }
                out.line(line);
                if (codeIndent(line) > 0) {
                    out.indent(1);
                }
            }
        }
    }

    private static int codeIndent(String line) {
        int indent = 0;
        for (char c : line.toCharArray()) {
            switch (c) {
                case '}': indent--; break;
                case '{': indent++; break;
            }
        }
        return indent;
    }

    private String mungePath(String path) {
        return path.replaceAll("/", "__");
    }

    interface Out {
        void line(String line);
        void indent(int change);
    }

    // observable

    public interface Listener {
        void mappingChanged(RecordMapping recordMapping);
    }

    public void addListener(Listener listener) {
        listeners.add(listener);
    }

    private List<Listener> listeners = new CopyOnWriteArrayList<Listener>();

    private void fireChangeEvent() {
        for (Listener listener : listeners) {
            listener.mappingChanged(this);
        }
    }

    // ==== reading and writing

    public static RecordMapping read(InputStream inputStream) {
        return (RecordMapping) stream().fromXML(inputStream);
    }

    public static RecordMapping read(String string) {
        return (RecordMapping) stream().fromXML(string);
    }

    public static String toString(RecordMapping spec) {
        return stream().toXML(spec);
    }

    private static XStream stream() {
        XStream stream = new XStream();
        stream.processAnnotations(RecordMapping.class);
        return stream;
    }
}
