/*
 * Copyright 2007 EDL FOUNDATION
 *
 * Licensed under the EUPL, Version 1.0 or - as soon they
 * will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence");
 * you may not use this work except in compliance with the
 * Licence.
 * You may obtain a copy of the Licence at:
 *
 * http://ec.europa.eu/idabc/eupl
 *
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
 */

package eu.europeana.core.querymodel.query;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Gerald de Jong <geralddejong@gmail.com>
 * @author Sjoerd Siebinga <sjoerd.siebinga@gmail.com>
 */

public class Language {
    private String code;
    private String name;
    private String [] alternatives;

    public static Language get(String code, boolean required) {
        Language language = LANGUAGE_MAP.get(code);
        if (required && language == null) {
            throw new IllegalArgumentException("Do not recognize language code: [" +code+"]");
        }
        return language;
    }

    private Language(String code, String name, String... alternatives) {
        this.code = code;
        this.name = name;
        this.alternatives = alternatives;
    }

    public String getCode() {
        return code;
    }

    public String getName() {
        return name;
    }

    public String[] getAlternatives() {
        return alternatives;
    }

    public String toString() {
        return code+":"+name;
    }

    private static Map<String, Language> LANGUAGE_MAP = new HashMap<String,Language>();

    private static Language [] LANGUAGES = {
        new Language("aa","Afar", "aar"),
        new Language("ab","Abkhazian", "abk"),
        new Language("ace","Achinese"),
        new Language("ach","Acoli"),
        new Language("ada","Adangme"),
        new Language("ady","Adyghe; Adygei"),
        new Language("ae","Avestan", "ave"),
        new Language("af","Afrikaans", "afr"),
        new Language("afa","Afro-Asiatic (Other),"),
        new Language("afh","Afrihili"),
        new Language("ak","Akan", "aka"),
        new Language("akk","Akkadian"),
        new Language("ale","Aleut"),
        new Language("alg","Algonquian languages"),
        new Language("alt","Southern Altai"),
        new Language("am","Amharic", "amh"),
        new Language("an","Aragonese"),
        new Language("ang","English, Old (ca.450-1100),"),
        new Language("apa","Apache languages"),
        new Language("ar","Arabic", "ara", "arabă"),
        new Language("arc","Aramaic"),
        new Language("arg","Aragonese"),
        new Language("arn","Araucanian"),
        new Language("arp","Arapaho"),
        new Language("art","Artificial (Other),"),
        new Language("arw","Arawak"),
        new Language("as","Assamese", "asm"),
        new Language("ast","Asturian; Bable"),
        new Language("ath","Athapascan languages"),
        new Language("aus","Australian languages"),
        new Language("av","Avaric", "ava"),
        new Language("awa","Awadhi"),
        new Language("ay","Aymara", "aym"),
        new Language("az","Azerbaijani", "aze"),
        new Language("ba","Bashkir", "bak"),
        new Language("bad","Banda"),
        new Language("bai","Bamileke languages"),
        new Language("bal","Baluchi"),
        new Language("bam","Bambara"),
        new Language("ban","Balinese"),
        new Language("bas","Basa"),
        new Language("bat","Baltic (Other),"),
        new Language("be","Belarusian", "bel"),
        new Language("bej","Beja"),
        new Language("bem","Bemba"),
        new Language("bn","Bengali", "ben"),
        new Language("ber","Berber (Other),"),
        new Language("bg","Bulgarian", "bul"),
        new Language("bh","Bihari"),
        new Language("bho","Bhojpuri"),
        new Language("bi","Bislama"),
        new Language("bih","Bihari"),
        new Language("bik","Bikol"),
        new Language("bin","Bini"),
        new Language("bis","Bislama"),
        new Language("bla","Siksika"),
        new Language("bm","Bambara"),
        new Language("bnt","Bantu (Other),"),
        new Language("bo","Tibetan", "bod"),
        new Language("br","Breton", "bre"),
        new Language("bra","Braj"),
        new Language("bs","Bosnian", "bos"),
        new Language("btk","Batak (Indonesia),"),
        new Language("bua","Buriat"),
        new Language("bug","Buginese"),
        new Language("byn","Blin; Bilin"),
        new Language("ca","Catalan; Valencian", "cat", "catalan"),
        new Language("cad","Caddo"),
        new Language("cai","Central American Indian (Other),"),
        new Language("car","Carib"),
        new Language("cau","Caucasian (Other),"),
        new Language("ce","Chechen", "che"),
        new Language("ceb","Cebuano"),
        new Language("cel","Celtic (Other),"),
        new Language("ch","Chamorro"),
        new Language("cha","Chamorro"),
        new Language("chb","Chibcha"),
        new Language("chg","Chagatai"),
        new Language("chk","Chuukese"),
        new Language("chm","Mari"),
        new Language("chn","Chinook jargon"),
        new Language("cho","Choctaw"),
        new Language("chp","Chipewyan"),
        new Language("chr","Cherokee"),
        new Language("chu","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
        new Language("chv","Chuvash"),
        new Language("chy","Cheyenne"),
        new Language("cmc","Chamic languages"),
        new Language("co","Corsican"),
        new Language("cop","Coptic"),
        new Language("cor","Cornish"),
        new Language("cos","Corsican"),
        new Language("cpe","Creoles and pidgins, English based (Other),"),
        new Language("cpf","Creoles and pidgins, French-based (Other),"),
        new Language("cpp","Creoles and pidgins, Portuguese-based (Other),"),
        new Language("cr","Cree", "cre"),
        new Language("crh","Crimean Tatar; Crimean Turkish"),
        new Language("crp","Creoles and pidgins (Other),"),
        new Language("cs","Czech", "cze", "ces"),
        new Language("csb","Kashubian"),
        new Language("cu","Old Bulgarian; Old Slavonic; Church Slavonic; Church Slavic; Old Church Slavonic"),
        new Language("cus","Cushitic (Other),"),
        new Language("cv","Chuvash"),
        new Language("cy","Welsh", "cym"),
        new Language("da","Danish", "dan", "danish"),
        new Language("dak","Dakota"),
        new Language("dar","Dargwa"),
        new Language("day","Dayak"),
        new Language("de","German", "deu", "ger", "german"),
        new Language("del","Delaware"),
        new Language("den","Slave (Athapascan),"),
        new Language("dgr","Dogrib"),
        new Language("din","Dinka"),
        new Language("div","Divehi"),
        new Language("doi","Dogri"),
        new Language("dra","Dravidian (Other),"),
        new Language("dsb","Lower Sorbian"),
        new Language("dua","Duala"),
        new Language("dum","Dutch, Middle (ca.1050-1350),"),
        new Language("dv","Divehi"),
        new Language("dyu","Dyula"),
        new Language("dz","Dzongkha"),
        new Language("dzo","Dzongkha"),
        new Language("ee","Ewe"),
        new Language("efi","Efik"),
        new Language("egy","Egyptian (Ancient),"),
        new Language("eka","Ekajuk"),
        new Language("el","Greek, Modern (1453-)", "ell", "gre", "greacă", "greaca", "greek"),
        new Language("elx","Elamite"),
        new Language("en","English", "eng", "uk", "us", "engleză", "english"),
        new Language("enm","English, Middle (1100-1500),"),
        new Language("eo","Esperanto", "epo"),
        new Language("es","Castilian; Spanish", "spa", "spanish"),
        new Language("et","Estonian", "est"),
        new Language("eu","Basque", "eus"),
        new Language("ewe","Ewe"),
        new Language("ewo","Ewondo"),
        new Language("fa","Persian", "fas"),
        new Language("fan","Fang"),
        new Language("fao","Faroese"),
        new Language("fas","Persian"),
        new Language("fat","Fanti"),
        new Language("ff","Fulah"),
        new Language("fi","Finnish", "fin", "finnish"),
        new Language("fij","Fijian"),
        new Language("fil","Filipino; Pilipino"),
        new Language("fiu","Finno-Ugrian (Other),"),
        new Language("fj","Fijian"),
        new Language("fo","Faroese"),
        new Language("fon","Fon"),
        new Language("fr","French", "fre", "fra", "french", "fro", "frm"),
        new Language("ful","Fulah"),
        new Language("fur","Friulian"),
        new Language("fy","Frisian", "fry"),
        new Language("ga","Irish", "gle"),
        new Language("gaa","Ga"),
        new Language("gay","Gayo"),
        new Language("gba","Gbaya"),
        new Language("gd","Scottish Gaelic; Gaelic"),
        new Language("gem","Germanic (Other),"),
//            new Language("ger","German"),
        new Language("gez","Geez"),
        new Language("gil","Gilbertese"),
        new Language("gl","Gallegan"),
        new Language("gla","Gaelic; Scottish Gaelic"),
        new Language("glg","Gallegan"),
        new Language("glv","Manx"),
        new Language("gmh","German, Middle High (ca.1050-1500),"),
        new Language("gn","Guarani"),
        new Language("goh","German, Old High (ca.750-1050),"),
        new Language("gon","Gondi"),
        new Language("gor","Gorontalo"),
        new Language("got","Gothic"),
        new Language("grb","Grebo"),
        new Language("grc","Greek, Ancient (to 1453),"),
        new Language("grn","Guarani"),
        new Language("gu","Gujarati"),
        new Language("guj","Gujarati"),
        new Language("gv","Manx"),
        new Language("gwi","Gwich�in"),
        new Language("ha","Hausa"),
        new Language("hai","Haida"),
        new Language("hat","Haitian; Haitian Creole"),
        new Language("hau","Hausa"),
        new Language("haw","Hawaiian"),
        new Language("he","Hebrew", "heb"),
        new Language("her","Herero"),
        new Language("hi","Hindi"),
        new Language("hil","Hiligaynon"),
        new Language("him","Himachali"),
        new Language("hin","Hindi"),
        new Language("hit","Hittite"),
        new Language("hmn","Hmong"),
        new Language("hmo","Hiri Motu"),
        new Language("ho","Hiri Motu"),
        new Language("hr","Croatian", "hrv"),
        new Language("hsb","Upper Sorbian"),
        new Language("ht","Haitian; Haitian Creole"),
        new Language("hu","Hungarian", "hun", "hungarian"),
        new Language("hup","Hupa"),
        new Language("hy","Armenian", "hye", "arm", "armeană"),
        new Language("hz","Herero"),
        new Language("ia","Interlingua (International Auxiliary Language Association),"),
        new Language("iba","Iban"),
        new Language("ibo","Igbo"),
        new Language("id","Indonesian"),
        new Language("ido","Ido"),
        new Language("ie","Interlingue"),
        new Language("ig","Igbo"),
        new Language("iii","Sichuan Yi"),
        new Language("ijo","Ijo"),
        new Language("ik","Inupiaq"),
        new Language("iku","Inuktitut"),
        new Language("ile","Interlingue"),
        new Language("ilo","Iloko"),
        new Language("ina","Interlingua (International Auxiliary Language Association),"),
        new Language("inc","Indic (Other),"),
        new Language("ind","Indonesian"),
        new Language("ine","Indo-European (Other),"),
        new Language("inh","Ingush"),
        new Language("io","Ido"),
        new Language("ipk","Inupiaq"),
        new Language("ira","Iranian (Other),"),
        new Language("iro","Iroquoian languages"),
        new Language("is","Icelandic", "isl"),
        new Language("it","Italian", "ita", "italian"),
        new Language("iu","Inuktitut"),
        new Language("ja","Japanese", "jpn"),
        new Language("jbo","Lojban"),
        new Language("jpr","Judeo-Persian"),
        new Language("jrb","Judeo-Arabic"),
        new Language("jv","Javanese", "jav"),
        new Language("ka","Georgian", "kat"),
        new Language("kaa","Kara-Kalpak"),
        new Language("kab","Kabyle"),
        new Language("kac","Kachin"),
        new Language("kal","Kalaallisut; Greenlandic"),
        new Language("kam","Kamba"),
        new Language("kan","Kannada"),
        new Language("kar","Karen"),
        new Language("kas","Kashmiri"),
        new Language("kau","Kanuri"),
        new Language("kaw","Kawi"),
        new Language("kaz","Kazakh"),
        new Language("kbd","Kabardian"),
        new Language("kg","Kongo"),
        new Language("kha","Khasi"),
        new Language("khi","Khoisan (Other),"),
        new Language("khm","Khmer"),
        new Language("kho","Khotanese"),
        new Language("ki","Kikuyu; Gikuyu"),
        new Language("kik","Kikuyu; Gikuyu"),
        new Language("kin","Kinyarwanda"),
        new Language("kir","Kirghiz"),
        new Language("kj","Kuanyama; Kwanyama"),
        new Language("kk","Kazakh"),
        new Language("kl","Kalaallisut; Greenlandic", "kal"),
        new Language("km","Khmer"),
        new Language("kmb","Kimbundu"),
        new Language("kn","Kannada"),
        new Language("ko","Korean"),
        new Language("kok","Konkani"),
        new Language("kom","Komi"),
        new Language("kon","Kongo"),
        new Language("kor","Korean"),
        new Language("kos","Kosraean"),
        new Language("kpe","Kpelle"),
        new Language("kr","Kanuri"),
        new Language("krc","Karachay-Balkar"),
        new Language("kro","Kru"),
        new Language("kru","Kurukh"),
        new Language("ks","Kashmiri"),
        new Language("ku","Kurdish"),
        new Language("kua","Kuanyama; Kwanyama"),
        new Language("kum","Kumyk"),
        new Language("kur","Kurdish"),
        new Language("kut","Kutenai"),
        new Language("kv","Komi"),
        new Language("kw","Cornish"),
        new Language("ky","Kirghiz"),
        new Language("la","Latin", "lat", "latină"),
        new Language("lad","Ladino"),
        new Language("lah","Lahnda"),
        new Language("lam","Lamba"),
        new Language("lao","Lao"),
        new Language("lb","Letzeburgesch; Luxembourgish"),
        new Language("lez","Lezghian"),
        new Language("lg","Ganda"),
        new Language("li","Limburgan; Limburger; Limburgish", "lim"),
        new Language("lin","Lingala"),
        new Language("ln","Lingala"),
        new Language("lo","Lao"),
        new Language("lol","Mongo"),
        new Language("loz","Lozi"),
        new Language("lt","Lithuanian", "lit"),
        new Language("ltz","Luxembourgish; Letzeburgesch"),
        new Language("lu","Luba-Katanga", "lub"),
        new Language("lua","Luba-Lulua"),
        new Language("lug","Ganda"),
        new Language("lui","Luiseno"),
        new Language("lun","Lunda"),
        new Language("luo","Luo (Kenya and Tanzania),"),
        new Language("lus","lushai"),
        new Language("lv","Latvian", "lat"),
        new Language("mad","Madurese"),
        new Language("mag","Magahi"),
        new Language("mah","Marshallese"),
        new Language("mai","Maithili"),
        new Language("mak","Makasar"),
        new Language("mal","Malayalam"),
        new Language("man","Mandingo"),
        new Language("map","Austronesian (Other),"),
        new Language("mar","Marathi"),
        new Language("mas","Masai"),
        new Language("mdf","Moksha"),
        new Language("mdr","Mandar"),
        new Language("men","Mende"),
        new Language("mg","Malagasy"),
        new Language("mga","Irish, Middle (900-1200),"),
        new Language("mh","Marshallese"),
        new Language("mi","Maori"),
        new Language("mic","Mi'kmaq; Micmac"),
        new Language("min","Minangkabau"),
        new Language("mis","Miscellaneous languages"),
        new Language("mk","Macedonian", "mkd"),
        new Language("mkh","Mon-Khmer (Other),"),
        new Language("ml","Malayalam"),
        new Language("mlg","Malagasy"),
        new Language("mlt","Maltese"),
        new Language("mn","Mongolian"),
        new Language("mnc","Manchu"),
        new Language("mni","Manipuri"),
        new Language("mno","Manobo languages"),
        new Language("mo","Moldavian", "mol"),
        new Language("moh","Mohawk"),
        new Language("mol","Moldavian"),
        new Language("mos","Mossi"),
        new Language("mr","Marathi"),
        new Language("mri","Maori"),
        new Language("ms","Malay"),
        new Language("msa","Malay"),
        new Language("mt","Maltese"),
        new Language("mul","Multiple languages"),
        new Language("mun","Munda languages"),
        new Language("mus","Creek"),
        new Language("mwl","Mirandese"),
        new Language("mwr","Marwari"),
        new Language("my","Burmese"),
        new Language("mya","Burmese"),
        new Language("myn","Mayan languages"),
        new Language("myv","Erzya"),
        new Language("na","Nauru"),
        new Language("nah","Nahuatl"),
        new Language("nai","North American Indian"),
        new Language("nap","Neapolitan"),
        new Language("nau","Nauru"),
        new Language("nav","Navajo; Navaho"),
        new Language("nb","Norwegian Bokmål; Bokmål", "nob"),
        new Language("nbl","Ndebele, South; South Ndebele"),
        new Language("nd","North Ndebele"),
        new Language("nde","Ndebele, North; North Ndebele"),
        new Language("ndo","Ndonga"),
        new Language("nds","Low German; Low Saxon; German, Low; Saxon, Low"),
        new Language("ne","Nepali"),
        new Language("nep","Nepali"),
        new Language("new","Newari; Nepal Bhasa"),
        new Language("ng","Ndonga"),
        new Language("nia","Nias"),
        new Language("nic","Niger-Kordofanian (Other),"),
        new Language("niu","Niuean"),
        new Language("nl","Dutch; Flemish", "nld", "dut", "dutch"),
        new Language("nn","Norwegian Nynorsk; Nynorsk, Norwegian", "nno"),
        new Language("no","Norwegian", "nor", "norwegian"),
        new Language("nog","Nogai"),
        new Language("non","Norse, Old"),
        new Language("nr","South Ndebele"),
        new Language("nso","Northern Sotho, Pedi; Sepedi"),
        new Language("nub","Nubian languages"),
        new Language("nv","Navaho"),
        new Language("nwc","Classical Newari; Old Newari; Classical Nepal Bhasa"),
        new Language("ny","Nyanja; Chichewa; Chewa"),
        new Language("nya","Chichewa; Chewa; Nyanja"),
        new Language("nym","Nyamwezi"),
        new Language("nyn","Nyankole"),
        new Language("nyo","Nyoro"),
        new Language("nzi","Nzima"),
        new Language("oc","Occitan (post 1500),; Proven�al"),
        new Language("oci","Occitan (post 1500),; Proven�al"),
        new Language("oj","Ojibwa"),
        new Language("oji","Ojibwa"),
        new Language("om","Oromo"),
        new Language("or","Oriya"),
        new Language("ori","Oriya"),
        new Language("orm","Oromo"),
        new Language("os","Ossetian; Ossetic"),
        new Language("osa","Osage"),
        new Language("oss","Ossetian; Ossetic"),
        new Language("ota","Turkish, Ottoman (1500-1928),"),
        new Language("oto","Otomian languages"),
        new Language("pa","Panjabi; Punjabi"),
        new Language("paa","Papuan (Other),"),
        new Language("pag","Pangasinan"),
        new Language("pal","Pahlavi"),
        new Language("pam","Pampanga"),
        new Language("pan","Panjabi; Punjabi"),
        new Language("pap","Papiamento"),
        new Language("pau","Palauan"),
        new Language("peo","Persian, Old (ca.600-400 B.C.),"),
        new Language("phi","Philippine (Other),"),
        new Language("phn","Phoenician"),
        new Language("pi","Pali"),
        new Language("pl","Polish", "pol"),
        new Language("pli","Pali"),
        new Language("pon","Pohnpeian"),
        new Language("por","Portuguese"),
        new Language("pra","Prakrit languages"),
        new Language("pro","Proven�al, Old (to 1500),"),
        new Language("ps","Pushto"),
        new Language("pt","Portuguese", "por"),
        new Language("pus","Pushto"),
        new Language("qu","Quechua", "que"),
        new Language("raj","Rajasthani"),
        new Language("rap","Rapanui"),
        new Language("rar","Rarotongan"),
        new Language("rm","Raeto-Romance"),
        new Language("rn","Rundi"),
        new Language("ro","Romanian", "ron", "romanian"),
        new Language("roa","Romance (Other),"),
        new Language("roh","Raeto-Romance"),
        new Language("rom","Romany"),
        new Language("ru","Russian", "rus", "russian"),
        new Language("run","Rundi"),
        new Language("rw","Kinyarwanda"),
        new Language("sa","Sanskrit", "san"),
        new Language("sad","Sandawe"),
        new Language("sag","Sango"),
        new Language("sah","Yakut"),
        new Language("sai","South American Indian (Other),"),
        new Language("sal","Salishan languages"),
        new Language("sam","Samaritan Aramaic"),
        new Language("sas","Sasak"),
        new Language("sat","Santali"),
        new Language("sc","Sardinian","srd"),
        new Language("scn","Sicilian"),
        new Language("sco","Scots"),
        new Language("sd","Sindhi"),
        new Language("se","Northern Sami"),
        new Language("sel","Selkup"),
        new Language("sem","Semitic (Other),"),
        new Language("sg","Sango"),
        new Language("sga","Irish, Old (to 900),"),
        new Language("sgn","Sign Languages"),
        new Language("shn","Shan"),
        new Language("si","Sinhala; Sinhalese"),
        new Language("sid","Sidamo"),
        new Language("sin","Sinhala ; Sinhalese"),
        new Language("sio","Siouan languages"),
        new Language("sit","Sino-Tibetan (Other),"),
        new Language("sk","Slovak", "slk"),
        new Language("sl","Slovenian", "slv"),
        new Language("sla","Slavic (Other)", "slavonă"),
        new Language("sm","Samoan", "smo"),
        new Language("sma","Southern Sami"),
        new Language("sme","Northern Sami"),
        new Language("smi","Sami languages (Other),"),
        new Language("smj","Lule Sami"),
        new Language("smn","Inari Sami"),
        new Language("sms","Skolt Sami"),
        new Language("sn","Shona"),
        new Language("sna","Shona"),
        new Language("snd","Sindhi"),
        new Language("snk","Soninke"),
        new Language("so","Somali"),
        new Language("sog","Sogdian"),
        new Language("som","Somali"),
        new Language("son","Songhai"),
        new Language("son","Songhai"),
        new Language("sot","Sotho, Southern"),
        new Language("sq","Albanian", "sqi", "albanian"),
        new Language("sr","Serbian", "srp"),
//        new Language("scr","Serbo-Croatian"),
        new Language("srr","Serer"),
        new Language("ss","Swati"),
        new Language("ssa","Nilo-Saharan (Other),"),
        new Language("ssw","Swati"),
        new Language("st","Sotho, Southern"),
        new Language("su","Sundanese"),
        new Language("suk","Sukuma"),
        new Language("sun","Sundanese"),
        new Language("sus","Susu"),
        new Language("sux","Sumerian"),
        new Language("sv","Swedish", "swe", "swedish"),
        new Language("sw","Swahili"),
        new Language("swa","Swahili"),
        new Language("syr","Syriac"),
        // T
        new Language("ta","Tamil", "tam"),
        new Language("tah","Tahitian"),
        new Language("tai","Tai (Other)"),
        new Language("tat","Tatar"),
        new Language("te","Telugu", "tel"),
        new Language("tem","Timne"),
        new Language("ter","Tereno"),
        new Language("tet","Tetum"),
        new Language("tg","Tajik", "tgk"),
        new Language("tgl","Tagalog"),
        new Language("th","Thai","tha"),
        new Language("ti","Tigrinya", "tir"),
        new Language("tig","Tigre"),
        new Language("tiv","Tiv"),
        new Language("tk","Turkmen", "tuk"),
        new Language("tkl","Tokelau"),
        new Language("tl","Tagalog"),
        new Language("tlh","Klingon; tlh I ngan-Hol"),
        new Language("tli","Tlingit"),
        new Language("tmh","Tamashek"),
        new Language("tn","Tswana", "tsn"),
        new Language("to","Tonga (Tonga Islands)","ton"),
        new Language("tog","Tonga (Nyasa),"),
        new Language("tpi","Tok Pisin"),
        new Language("tr","Turkish", "tur", "turkish"),
        new Language("ts","Tsonga", "tso"),
        new Language("tsi","Tsimshian"),
        new Language("tt","Tatar"),
        new Language("tum","Tumbuka"),
        new Language("tup","Tupi languages"),
        new Language("tut","Altaic (Other),"),
        new Language("tvl","Tuvalu"),
        new Language("tw","Twi", "twi"),
        new Language("ty","Tahitian"),
        new Language("tyv","Tuvinian"),
        // U
        new Language("udm","Udmurt"),
        new Language("ug","Uyghur; Uighur", "uig"),
        new Language("uga","Ugaritic"),
        new Language("uk","Ukrainian", "ukr"),
        new Language("umb","Umbundu"),
        new Language("und","Undetermined"),
        new Language("ur","Urdu", "urd"),
        new Language("uz","Uzbek", "uzb"),
        // V
        new Language("vai","Vai"),
        new Language("ve","Venda", "ven"),
        new Language("vi","Vietnamese", "vie"),
        new Language("vo","Volapük", "vol"),
        new Language("vot","Votic"),
        new Language("wa","Walloon"),
        new Language("wak","Wakashan languages"),
        new Language("wal","Walamo"),
        new Language("war","Waray"),
        new Language("was","Washo"),
        new Language("wen","Sorbian languages"),
        new Language("wln","Walloon"),
        new Language("wo","Wolof", "wol"),
        // X
        new Language("xal","Kalmyk"),
        new Language("xh","Xhosa", "xho"),
        // Y
        new Language("yao","Yao"),
        new Language("yap","Yapese"),
        new Language("yi","Yiddish", "yid"),
        new Language("yo","Yoruba", "yor"),
        new Language("ypk","Yupik languages"),
        // Z
        new Language("za","Zhuang; Chuang", "zha"),
        new Language("zap","Zapotec"),
        new Language("zen","Zenaga"),
        new Language("zh","Chinese", "zho"),
        new Language("znd","Zande"),
        new Language("zu","Zulu", "zul"),
        new Language("zun","Zuni"),
//        new Language("ON","..."),
//        new Language("nem","..."),
//        new Language("UNKNOWN","..."),
    };

    static {
        for (Language language : LANGUAGES) {
            LANGUAGE_MAP.put(language.getCode(), language);
            LANGUAGE_MAP.put(language.getCode().toUpperCase(), language);
            for (String alternative : language.getAlternatives()) {
                LANGUAGE_MAP.put(alternative, language);
                LANGUAGE_MAP.put(alternative.toUpperCase(), language);
            }
        }
    }


}
